#! /bin/sh
#
# EFS Plugin for Midnight Commander
#
# You need to specify the path and name of the qefs program here, as well as, if necessary, the -p flag to specify a specific port
#
qefs="/usr/share/qtools/qefs -p0"

#***********************************
# Get the list of files
#***********************************

efs_list() {
$qefs -lm $1 
}

#***********************************
# Extract files
#***********************************
efs_copyout() {
$qefs -gf $2 $3
}

#***********************************
# Write files
#***********************************
efs_copyin() {
$qefs -wf $3 $2
}

#***********************************
# Remove files
#***********************************
efs_rm() {
$qefs -ef $2
}

#***********************************
# Create a directory
#***********************************
efs_mkdir() {
$qefs -md $2 rwx
}

#***********************************
# Remove a directory
#***********************************
efs_rmdir() {
$qefs -ed $2 
}


umask 077

cmd="$1"
shift

case "$cmd" in
  list)    efs_list    "$@" ;;
  rm)      efs_rm      "$@" ;;
  rmdir)   efs_rmdir   "$@" ;;
  mkdir)   efs_mkdir   "$@" ;;
  copyin)  efs_copyin  "$@" ;;
  copyout) efs_copyout "$@" ;;
  *) exit 1 ;;
esac
exit 0
