#! /bin/sh
#
# EFS-Plugin for Midnight Commander
#
# Here you need to enter the path and name of the QEFS program, as well as, if necessary, the key -p to specify a particular port
#
qefs="/usr/share/qtools/qefs -p0"

#***********************************
# Getting a list of files
#***********************************

efs_list() {
$qefs -lm $1 
}

#***********************************
# Retrieving Files
#***********************************
efs_copyout() {
$qefs -gf $2 $3
}

#***********************************
# Writing files
#***********************************
efs_copyin() {
$qefs -wf $3 $2
}

#***********************************
# Deleting files
#***********************************
efs_rm() {
$qefs -ef $2
}

#***********************************
# Creating a Folder
#***********************************
efs_mkdir() {
$qefs -md $2 rwx
}

#***********************************
# Deleting a Folder
#***********************************
efs_rmdir() {
$qefs -ed $2 
}


umask 077

cmd="$1"
shift

case "$cmd" in
  list)    efs_list    "$@" ;;
  rm)      efs_rm      "$@" ;;
  rmdir)   efs_rmdir   "$@" ;;
  mkdir)   efs_mkdir   "$@" ;;
  copyin)  efs_copyin  "$@" ;;
  copyout) efs_copyout "$@" ;;
  *) exit 1 ;;
esac
exit 0
